# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
